### ISSUE TITLE
Unable to open PDF in Adobe Reader DC

### ISSUE THREAD

**Issue by 1xcodex1** [reingart/pyfpdf#87] opened 2017-04-30 12:18 UTC
pyfpdf version: 1.7.2
Adobe Reader version: 2017.009.20044

To examine the problem I tested pypdf using the script containing header, footer, etc. from:
http://pyfpdf.readthedocs.io/en/latest/Tutorial/index.html
... without success.

I resaved the corrupted file with PDF-XChange Viewer. After this I was able to open it in AR.

By the way, SumatraPDF and PDF-XChange Viewer show the file without complaining.

**Comment by RomanKharin** [comment] 2017-04-30 12:25
1xcodex1, did you try version from master.
We recently fix horrible bug #78
You can check this searching inside PDF with text viewer for pattern 'Transparency"\\n                    "/CS'

**Comment by RomanKharin** [comment] 2017-04-30 12:45
Can you provide PDF sample here?

**Comment by 1xcodex1** [comment] 2017-04-30 12:52
Hi, thanks for the fast reply!
I tried this one:
https://github.com/alexanderankin/pyfpdf

It is working as expected. Excellent!

**Comment by 1xcodex1** [comment] 2017-04-30 13:00
I've been taken a look into the (corrupted) file, and yes, there are multiple statements like:

/Group <</Type /Group /S /Transparency" ....... whitespaces ........ "/CS /DeviceRGB>>

Probably this is, what you mean.

**Comment by RomanKharin** [comment] 2017-04-30 13:10
Duplicate of #78

**Closed by RomanKharin** 2017-04-30 13:10 UTC
